// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxtusonvccivnzwxkjok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dHVzb252Y2Npdm56d3hram9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDE0ODYsImV4cCI6MjA2MDExNzQ4Nn0.rUomMRv5l_iNQ-bYs2F8YSmqWFpNyyr9fvS4tqXjK4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);